name: run-tests
on: [push]
jobs:
  test-utils:
    name: 2022 utils tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup Deno
        uses: denoland/setup-deno@v1.1.1
        with:
          deno-version: "^1.28.2"
      - name: Run 2022 utils tests
        working-directory: "2022"
        run: deno test utils.test.ts
