name: run-tests
on: [push]
jobs:
  test-utils:
   runs-on: ubuntu-latest
   steps:
      - name: Setup Deno
        uses: denoland/setup-deno@v1.1.1
      - name: Run 2022 utils tests
        working-directory: ./2022
        run: deno test utils.test.ts
